### ISSUE TITLE
npm failing to find a package

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#124]
I have a package called [davemail](https://www.npmjs.com/package/davemail).

It's really simple, it just contains a function that sends an email message through Amazon SES. 

I have a project that just includes davemail. You can download the folder [here](http://scripting.com/2019/08/20/testDavemail.zip). 

1. Open the folder in your Terminal app.
1. npm install
2. node test.js

I get this message.

```
Error: Cannot find module 'davemail'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/Dropbox/Rockaway3/scriptingnightlyemail/scriptingnightlyemail.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

Does it happen for you too?

I get it only on this package. I have quite a few others that work without problem. 

On my machine the folder is there in npm_modules.

**Comment by tedchoward** [comment]
I can reproduce this exactly on my machine.

This is just a wild guess, but did you specify a `main` script in your `package.json` file inside the `davemail` module? (https://docs.npmjs.com/files/package.json#main)

**Comment by scripting** [comment]
Ted, thanks for the tip -- that was it. I made the change, added a main script and it worked. ;-)
