### ISSUE TITLE
Runtime error in script run via eval crashes the app

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#127]
PagePark allows pages to be defined by script, the way it works is if a file has a .js extension it runs it through an eval inside a try.

The idea is that if your script has an error, we can catch it so it doesn't crash PagePark. 

But it doesn't get caught and PagePark crashes. 

Not sure what script it's running, I'm adding some debugging code to list that to the console, but in the meantime I wonder if there is a legit way in JS to catch these errors. I'd like to log them, and of course PP should keep running.

PS: Please save the lectures about security. I have decades of experience with this. Thanks. :-)

**Comment by danmactough** [comment]
> But it doesn't get caught and PagePark crashes.

If the JavaScript getting `eval`'d has any asynchronous code, try/catch won't catch that.

Example:

```
> // Non-async code
undefined
> s = "throw new Error('eval me')"
'throw new Error(\'eval me\')'
> try { eval(s) } catch (e) { console.error(`An error was caught: ${e.message}`) }
An error was caught: eval me
undefined
> // Async code
undefined
> s = "process.nextTick(() => { throw new Error('eval me') } )"
'process.nextTick(() => { throw new Error(\'eval me\') } )'
> try { eval(s) } catch (e) { console.error(`An error was caught: ${e.message}`) }
undefined
> Error: eval me
    at process.nextTick (eval at <anonymous> (repl:1:7), <anonymous>:1:32)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

I'm confused to hear that PagePark crashes, though.

**Comment by scripting** [comment]
Dan that makes perfect sense. I should have included the stack crawl when PP crashes to give a clue. I added some debugging code and trapped the problem. It's a missing callback on a fs.writeFile call in the script that was being eval'd. Here's the actual script.

```
if (urlFeed !== undefined) {
	var now = new Date (), fname = "domains/ping.1999.io/pingers.json";
	console.log ("ping.1999.io: urlFeed == " + urlFeed);
	fs.readFile (fname, function (err, data) {
		var jstruct = new Object ();
		if (!err) {
			jstruct = JSON.parse (data.toString ());
			}
		if (jstruct [urlFeed] === undefined) {
			jstruct [urlFeed] = {
				ct: 1,
				when: now
				}
			}
		else {
			jstruct [urlFeed].ct++;
			jstruct [urlFeed].when = now
			}
		fs.writeFile (fname, JSON.stringify (jstruct, undefined, 4));
		});
	}
"Thanks for the ping!";
```
